#define BUFFSIZE 1024
#define FB_BUFFSIZE BUFFSIZE * 2
#define SK_BUFFSIZE BUFFSIZE * 2
#define READFILE_BUFFSIZE BUFFSIZE

#define PORT_COMMAND "20001"
#define PORT_DATA "20002"
#define INPUT_BUFFSIZE 4096

#define HASHSEED 0